export const ACCESS_ROLE_MAP: Record<string, string[]> = {
  PUBLIC: ['SUPER_ADMIN', 'ADMIN', 'KEPALA_SEKOLAH', 'TU', 'GURU', 'SISWA', 'AUDITOR'],
  INTERNAL: ['SUPER_ADMIN', 'ADMIN', 'KEPALA_SEKOLAH', 'TU', 'GURU'],
  RESTRICTED: ['SUPER_ADMIN', 'ADMIN', 'KEPALA_SEKOLAH', 'TU'],
  CONFIDENTIAL: ['SUPER_ADMIN', 'ADMIN', 'KEPALA_SEKOLAH', 'TU'],
  SECRET: ['SUPER_ADMIN', 'ADMIN', 'KEPALA_SEKOLAH'],
}
